export const COUNTER_FINISHED = 'COUNTER_FINISHED';
export const COUNTER_STARTED = 'COUNTER_STARTED';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';